// Generated by gencpp from file main/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MAIN_MESSAGE_ADDTWOINTS_H
#define MAIN_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <main/AddTwoIntsRequest.h>
#include <main/AddTwoIntsResponse.h>


namespace main
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace main


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::main::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::main::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::main::AddTwoInts > {
  static const char* value()
  {
    return "main/AddTwoInts";
  }

  static const char* value(const ::main::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::main::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::main::AddTwoInts > 
template<>
struct MD5Sum< ::main::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::main::AddTwoInts >::value();
  }
  static const char* value(const ::main::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::main::AddTwoIntsRequest> should match 
// service_traits::DataType< ::main::AddTwoInts > 
template<>
struct DataType< ::main::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::main::AddTwoInts >::value();
  }
  static const char* value(const ::main::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::main::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::main::AddTwoInts > 
template<>
struct MD5Sum< ::main::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::main::AddTwoInts >::value();
  }
  static const char* value(const ::main::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::main::AddTwoIntsResponse> should match 
// service_traits::DataType< ::main::AddTwoInts > 
template<>
struct DataType< ::main::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::main::AddTwoInts >::value();
  }
  static const char* value(const ::main::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAIN_MESSAGE_ADDTWOINTS_H
